w11d3/auth_prep/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

end

w11d3/auth_prep/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w11d3/auth_prep/app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :password_digest, presence: { message: 'Password can\'t be blank' }
    validates :password, length: { minimum: 6, allow_nil: true }

    attr_reader :password

    def password=(password) 
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end 
end

w11d3/auth_prep/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w11d3/auth_prep/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        @user = User.new(user_params)

        if @user.save
            render json: @user
        else
            render json: @user.errors.full_messages
        end
    end

    def new
        @user = User.new
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

w11d3/auth_prep/app/helpers/application_helper.rb
module ApplicationHelper
end

w11d3/auth_prep/app/helpers/users_helper.rb
module UsersHelper
end

w11d3/auth_prep/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthPrep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w11d3/auth_prep/app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>Create User</h1>

<%= render "form", user: @user %>

<!-- app/views/users/_form.html.erb -->
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>